import React, {useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {defaults,calculate,prices,type Settings} from './calculator';
import './style.css';
const KEY='chiba-kuji-settings-v1';
const format=(n:number)=>Math.round(n).toLocaleString('ko-KR');
const won=(n:number)=>`${format(n)}원`;
function initial():Settings {
  try {const saved=JSON.parse(localStorage.getItem(KEY)||'{}'); const result={...defaults};
    for(const k of Object.keys(defaults) as (keyof Settings)[]) {
      const v=saved[k];const d=defaults[k];
      if(typeof d==='number' && typeof v==='number' && Number.isFinite(v) && v>=0 && (!['tickets','lots','batch'].includes(k)||(Number.isInteger(v)&&v>=1))) Object.assign(result,{[k]:v});
      else if(typeof d==='boolean'&&typeof v==='boolean') Object.assign(result,{[k]:v});
      else if(k==='shipping'&&(v==='air'||v==='sea')) result.shipping=v;
    } return result;
  } catch {return {...defaults};}
}
function App(){
  const [s,setS]=useState(initial);const [storageError,setStorageError]=useState(false);
  useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(s));setStorageError(false);}catch{setStorageError(true);}},[s]);
  const update=<K extends keyof Settings>(key:K,value:Settings[K])=>setS(old=>({...old,[key]:value}));
  const r=calculate(s);
  const input=(key:keyof Settings,label:string,unit:string,integer=false)=><label className="field" key={key}><span>{label}</span><div className="input-wrap"><input aria-label={label} type="number" min={integer?1:0} step={integer?1:'any'} value={String(s[key])} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=0&&(!integer||(n>=1&&Number.isInteger(n))))update(key,n as never);}}/><span>{unit}</span></div><small>{format(Number(s[key]))} {unit}</small></label>;
  const check=(key:keyof Settings,label:string)=><label className="check"><input type="checkbox" checked={Boolean(s[key])} onChange={e=>update(key,e.target.checked as never)}/>{label}</label>;
  const rows:[string,number,string][]=[['일본 상품 총매입비',r.purchase,''],['일본 국내 택배비',r.domestic,`${s.lots}로트`],['국제배송비',r.freight,`${r.shipments}회 발송 · ${s.manualFreight?'총액 직접 지정':s.shipping==='air'?'항공':'해운'}`],['관세',r.duty,`과세가격 ${won(r.customs)}`],['수입부가세 · 원가 반영',r.importCost,`통관 시 납부 ${won(r.importVat)}${s.importCredit?' · 전액 공제':''}`],['통관대행비',r.clearance,`${r.shipments}회`],['라이브쿠지 수수료 · 원가 반영',r.feeCost,`지급 ${won(r.feePaid)} · 부가세 ${won(r.feeVat)}`],['기타 배송·통관 비용',s.shippingOther,'전체 구매 기준'],['한국 포장·고객 배송비',s.localDelivery,'전체 판매 기준'],['기타 비용',s.other,'전체 구매·판매 기준']];
  return <main><header><div className="eyebrow">CHIBA KUJI / PROFIT CALCULATOR</div><h1>치바쿠지 마진 계산기<span>추정치</span></h1><p>구매부터 판매까지, 비용을 확인하고 판매가격을 결정하세요.</p></header>
  <section><div className="section-title"><h2><b>01</b> 구매 정보</h2><button onClick={()=>{if(window.confirm('입력한 모든 값을 기본값으로 초기화할까요?'))setS({...defaults});}}>기본값 초기화</button></div><div className="grid">{input('tickets','1로트당 쿠지 수량','장',true)}{input('ticketYen','쿠지 1장 구매가격','엔')}{input('lots','구매 로트 수','로트',true)}{input('exchange','100엔당 환율','원')}</div><div className="inset"><div><span>실제 1로트 구매가격</span><strong>{format(s.manualLot?s.lotYen:s.tickets*s.ticketYen)}엔</strong></div>{check('manualLot','로트 구매가격 직접 입력')}{s.manualLot&&input('lotYen','실제 로트 구매가격','엔')}</div></section>
  <section><h2><b>02</b> 배송 및 세금</h2><div className="shipping"><div className="segmented">{(['air','sea'] as const).map(v=><button aria-pressed={s.shipping===v} className={s.shipping===v?'active':''} onClick={()=>update('shipping',v)} key={v}>{v==='air'?'항공 배송':'해운 배송'}</button>)}</div><span>총 {s.lots}로트 / <strong>{r.shipments}회 발송</strong></span></div><div className="grid">{input('batch','한 번에 배송할 로트 수','로트',true)}{input('domestic','일본 국내 택배비 · 로트당','원')}{input('air','항공 운임 · 발송 1회당','원')}{input('sea','해운 운임 · 발송 1회당','원')}{input('clearance','통관대행비 · 발송 1회당','원')}{input('shippingOther','기타 배송·통관 비용 · 총액','원')}</div><div className="inset">{check('manualFreight','국제배송비 총액 직접 지정')}{s.manualFreight?input('freightTotal','국제배송비 총액','원'):<p>선택 운임 × 발송 횟수 = {won(r.freight)}. 묶음 배송 견적이 다르면 총액을 직접 지정하세요.</p>}</div><details open><summary>세율·수수료 및 추가 비용 설정</summary><div className="grid">{input('dutyRate','관세율','%')}{input('importVatRate','수입부가세율','%')}{input('salesVatRate','판매부가세율','%')}{input('feeRate','라이브쿠지 수수료율','%')}{input('feeVatRate','수수료 부가세율','%')}{input('localDelivery','한국 포장·고객 배송비 · 총액','원')}{input('other','기타 비용 · 총액','원')}</div><div className="checks">{check('importCredit','수입부가세 전액 매입세액 공제 가능')}{check('feeIncludesVat','입력한 수수료율에 부가세 포함')}{check('feeCredit','수수료 부가세 매입세액 공제 가능')}{check('manualCustoms','관세 과세가격 총액 직접 입력')}</div>{s.manualCustoms&&input('customsValue','관세 과세가격 · 전체 수입 총액','원')}<p className="note">기본 과세가격은 상품 매입비 + 일본 국내 택배비 + 국제배송비입니다. 수입부가세는 (과세가격 + 관세)에 적용합니다. 수수료는 소비자 결제 총매출에 적용하며, 부가세 미포함 선택 시 별도 부가세를 가산합니다.</p></details></section>
  <section className="results"><div className="section-title"><h2><b>03</b> 예상 판매 결과</h2><span>100% 완판 기준 · {format(s.tickets*s.lots)}장</span></div><div className="price-control">{input('price','기준 1회 판매가격','원')}<p>기준 가격을 입력하거나 아래 마진표에서 선택하세요.</p></div><div className="cards">{[['총매출 · 부가세 포함',won(r.gross)],['총비용 · 공제 반영',won(r.cost)],['예상 영업이익',won(r.profit)],['예상 영업이익률',`${r.margin.toFixed(2)}%`],['1로트당 예상 이익',won(r.lotProfit)]].map(([label,value],i)=><div className={'card '+(i===2||i===3?'highlight':'')} key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="note">판매 공급가액 {won(r.net)} · 판매부가세 {won(r.salesVat)}. 영업이익률은 부가세 제외 매출 기준입니다.</p><h3>전체 비용 내역</h3><div className="table-wrap"><table><thead><tr><th>비용 항목</th><th>계산 기준 / 납부액</th><th className="number">최종 원가</th></tr></thead><tbody>{rows.map(([label,value,note])=><tr key={label}><td>{label}</td><td className="muted">{note||'전체 구매 기준'}</td><td className="number">{won(value)}</td></tr>)}</tbody><tfoot><tr><th colSpan={2}>전체 비용 합계</th><th className="number">{won(r.cost)}</th></tr></tfoot></table></div><h3>판매가격별 마진율</h3><p className="note">판매가격을 누르면 해당 가격의 요약과 비용 내역을 확인할 수 있습니다.</p><div className="table-wrap"><table><thead><tr><th>1회 판매가격</th><th className="number">총매출 · VAT 포함</th><th className="number">예상 영업이익</th><th className="number">마진율</th></tr></thead><tbody>{prices.map(price=>{const v=calculate(s,price);return <tr key={price} className={price===s.price?'selected':''}><td><button className="price-button" onClick={()=>update('price',price)} aria-pressed={price===s.price}>{won(price)}{price===s.price&&<small> 기준</small>}</button></td><td className="number">{won(v.gross)}</td><td className={'number '+(v.profit<0?'negative':'')}>{won(v.profit)}</td><td className={'number '+(v.margin<0?'negative':'')}>{v.margin.toFixed(2)}%</td></tr>})}</tbody></table></div></section>
  <footer><strong>계산 결과는 추정치입니다.</strong><p>한국 일반과세자 기준이며 실제 수입세액은 품목별 관세율과 통관 조건에 따라 달라질 수 있습니다. 일본 소득세·주민세는 계산하지 않습니다. 계산 중간값은 반올림하지 않고 표시 금액만 원 단위로 반올림하므로 표시 항목의 합계와 총액에 소액 차이가 있을 수 있습니다.</p><span role="status">{storageError?'브라우저 저장을 사용할 수 없습니다. 새로고침하면 입력값이 사라질 수 있습니다.':'입력값은 이 브라우저에 자동 저장됩니다.'}</span></footer></main>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
